export const Images = {
    src: {
        logo: '/images/sure logo.png',
        logo2: '/images/surelogo.png',
        surebrandProducts: {
            hood1: '/images/HOOD1.png',
            hood2: '/images/HOOD2.png',
            hood3: '/images/HOOD3.png',
            shirt1: '/images/SHIRT 1.png',
            shirt2: '/images/SHIRT 2.png',
            shirt3: '/images/SHIRT 3.png',
            shirt4: '/images/SHIRT 4.png',
            shirt5: '/images/SHIRT 5.png',
            shirt6: '/images/SHIRT 6.png',
            shirt7: '/images/SHIRT 7.png',
            shirt8: '/images/SHIRT 8.png',
            shirt9: '/images/SHIRT 9.png',
            groupCaps1: '/images/group-caps-prints.jpg',
            groupShirts1: '/images/group-shirt-prints.jpg',
            bag1: '/images/BAG 1.png',
            bag2: '/images/BAG 2.png',
            shirtPrintingMachine3: '/images/shirt-printing-machine3.png',
            shirtPrintingMachine4: '/images/shirt-printing-machine4.png',
            umbrella1: '/images/UMBRELLA 1.png',
            umbrella2: '/images/UMBRELLA 2.png',
            waterBottle: '/images/WATER BOTTLE.png',
            mugGroup: '/images/MUG GROUP.png',
            mug1: '/images/MUG 1.png',
            mug3: '/images/MUG 3.png',
            sublishirt2: '/images/SUBLISHIRT 2.png',
            sublishirt3: '/images/SUBLISHIRT 3.png',
            cuttingPlotter1: 'images/cutting-plotter.jpg',
            materialPrintingMachine: '/images/material-printing-machine.jpg',
        }
    }
}